// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_Img': string;
  '_bottom': string;
  '_buyBtn': string;
  '_buyText': string;
  '_content': string;
  '_detail': string;
  '_item': string;
  '_list': string;
  'author': string;
  'chromeframe': string;
  'conInfo': string;
  'con_box': string;
  'content': string;
  'desc': string;
  'division': string;
  'modalTitle': string;
  'price': string;
  'title': string;
  'top_Item': string;
  'top_box': string;
  'wxCodeImg': string;
}
export const cssExports: CssExports;
export default cssExports;
