// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_content': string;
  'chromeframe': string;
  'conHtml': string;
  'con_box': string;
  'date': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
