// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_content': string;
  'active': string;
  'arrow': string;
  'c_item1': string;
  'c_item2': string;
  'c_title': string;
  'c_top': string;
  'chromeframe': string;
  'con_box': string;
  'con_section': string;
  'con_top': string;
  'course_top': string;
  'ctitle': string;
  'font_btn': string;
  'font_img': string;
  'font_structure': string;
  'left': string;
  'modalTitle': string;
  'ph_item': string;
  'phrase': string;
  'right': string;
  's_item': string;
  'st_item': string;
  'structure': string;
  'tItem': string;
  'tab_box': string;
  'title': string;
  'title_con': string;
  'top_box': string;
  'w_item': string;
  'words': string;
  'wxCodeImg': string;
}
export const cssExports: CssExports;
export default cssExports;
