// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_content': string;
  'banner': string;
  'chromeframe': string;
  'con_bottom': string;
  'con_box': string;
  'content': string;
  'desc': string;
  'iStyle': string;
  'introduce': string;
  'item': string;
  'title': string;
  'titleTxt': string;
}
export const cssExports: CssExports;
export default cssExports;
