// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_home': string;
  'banner': string;
  'bgImg': string;
  'c2Img': string;
  'cImg': string;
  'cImgItem': string;
  'chromeframe': string;
  'contentImg': string;
  'titleImg': string;
}
export const cssExports: CssExports;
export default cssExports;
