// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_content': string;
  'c_Img': string;
  'chromeframe': string;
  'content': string;
  'h_item': string;
  'h_title': string;
  'hotList': string;
  'newsList': string;
  's_News': string;
  'titleBox': string;
  'titleImg': string;
  'titleTxt': string;
}
export const cssExports: CssExports;
export default cssExports;
