// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_header': string;
  'btnActive': string;
  'chromeframe': string;
  'container': string;
  'down': string;
  'inputSearch': string;
  'logo': string;
  'menuItem': string;
  'menuList': string;
  'name': string;
  'noHomeStyle': string;
  'routerBtn': string;
  'search': string;
  'skin': string;
  'user': string;
}
export const cssExports: CssExports;
export default cssExports;
