// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_footer': string;
  'chromeframe': string;
  'containerWrapper': string;
  'drawer': string;
  'footerColumn': string;
  'footerColumns': string;
  'footerItem': string;
  'home': string;
  'iconAdd': string;
  'menu': string;
  'move': string;
  'textFont': string;
}
export const cssExports: CssExports;
export default cssExports;
